// Contract addresses on X Layer Mainnet (chain 196)
export const CONTRACTS = {
  // Core token
  fanovoToken: "0xe81de3d4db134d2E722Bc4A2E4f07e4A4231b131" as `0x${string}`,

  // Hooks
  worldCupHook: "0x77f375dc878c4d0416A9D0A6CC603b3F202b6AA8" as `0x${string}`,
  playerHook: "0xC8cA12C106F4aBa993F9b513CF0f2ea68E76eaa8" as `0x${string}`,

  // Factories
  countryFactory: "0xFb0C0feeCF70Aa4A632eDBbAf8FD4db722d128b3" as `0x${string}`,
  playerFactory: "0x1620cdadc2b298400eB4622606E7633A8DbBeBbF" as `0x${string}`,

  // Pack Openers
  packOpener: "0x0F1e733FB0c8934410987cfb12A66a2A42e0BB3B" as `0x${string}`,
  playerPackOpener: "0x3652C5c395092842680CC547a3cb0AD3e61C3cDc" as `0x${string}`,

  // Routers
  curveRouter: "0x28409b0A0162eAA90F78C00D8bB6625599934178" as `0x${string}`,
  playerRouter: "0xAC2d4135d64E175a6c35b26Fe11203595fAE1E1A" as `0x${string}`,

  // Market & Game
  predictionMarketHub: "0xF5E7617a81D3c3E4cE81caa6d166220E47ffB557" as `0x${string}`,
  lineupsGame: "0x57a74De5fa7Ae5f6aE23E0AA6c9eE187246e7c2b" as `0x${string}`,

  // Sale & Treasury
  fanovoSale: "0x492FcadaA3a959d162f585783D7671c0F61523cD" as `0x${string}`,
  fanovoTreasury: "0xAA28CC5434Eed5e597697599798D80c622705AeA" as `0x${string}`,

  // External
  usdt: "0x779Ded0c9e1022225f8E0630b35a9b54bE713736" as `0x${string}`,
  poolManager: "0x360E68faCcca8cA495c1B759Fd9EEe466db9FB32" as `0x${string}`,

} as const;

// Short address helper, e.g. 0xe81d…b131
export function shortAddress(addr: string, head = 4, tail = 4): string {
  if (!addr || addr.length < head + tail + 2) return addr;
  return `${addr.slice(0, 2 + head)}…${addr.slice(-tail)}`;
}

// Players data (144 players - 3 per country, matching on-chain order — PITCH canonical order)
export const PLAYERS = [
  { countryId: 0, name: "Christian Pulisic", role: 1 as const, position: "FW", symbol: "PULISIC" },
  { countryId: 0, name: "Tyler Adams", role: 0 as const, position: "MF", symbol: "ADAMS" },
  { countryId: 0, name: "Cavan Sullivan", role: 2 as const, position: "FW", symbol: "SULLIVAN" },
  { countryId: 1, name: "Santiago Giménez", role: 1 as const, position: "MF", symbol: "SGIMENEZ" },
  { countryId: 1, name: "Edson Álvarez", role: 0 as const, position: "DF", symbol: "ALVAREZ" },
  { countryId: 1, name: "Gilberto Mora", role: 2 as const, position: "MF", symbol: "GMORA" },
  { countryId: 2, name: "Alphonso Davies", role: 1 as const, position: "DF", symbol: "DAVIES" },
  { countryId: 2, name: "Jonathan David", role: 0 as const, position: "FW", symbol: "DAVID" },
  { countryId: 2, name: "Luc de Fougerolles", role: 2 as const, position: "MF", symbol: "FOUGEROLLES" },
  { countryId: 3, name: "Lionel Messi", role: 1 as const, position: "FW", symbol: "MESSI" },
  { countryId: 3, name: "Cristian Romero", role: 0 as const, position: "DF", symbol: "ROMERO" },
  { countryId: 3, name: "Nico Paz", role: 2 as const, position: "MF", symbol: "PAZ" },
  { countryId: 4, name: "Vinícius Júnior", role: 1 as const, position: "FW", symbol: "VINICIUS" },
  { countryId: 4, name: "Marquinhos", role: 0 as const, position: "DF", symbol: "MARQUINHOS" },
  { countryId: 4, name: "Estêvão", role: 2 as const, position: "FW", symbol: "ESTEVAO" },
  { countryId: 5, name: "Moisés Caicedo", role: 1 as const, position: "MF", symbol: "CAICEDO" },
  { countryId: 5, name: "Enner Valencia", role: 0 as const, position: "FW", symbol: "VALENCIA" },
  { countryId: 5, name: "Kendry Páez", role: 2 as const, position: "MF", symbol: "PAEZ" },
  { countryId: 6, name: "Federico Valverde", role: 1 as const, position: "MF", symbol: "VALVERDE" },
  { countryId: 6, name: "José María Giménez", role: 0 as const, position: "MF", symbol: "JGIMENEZ" },
  { countryId: 6, name: "Luciano Rodríguez", role: 2 as const, position: "MF", symbol: "RODRIGUEZ" },
  { countryId: 7, name: "Luis Díaz", role: 1 as const, position: "FW", symbol: "DIAZ" },
  { countryId: 7, name: "James Rodríguez", role: 0 as const, position: "MF", symbol: "JAMES" },
  { countryId: 7, name: "Yáser Asprilla", role: 2 as const, position: "FW", symbol: "ASPRILLA" },
  { countryId: 8, name: "Miguel Almirón", role: 1 as const, position: "MF", symbol: "ALMIRON" },
  { countryId: 8, name: "Gustavo Gómez", role: 0 as const, position: "MF", symbol: "GOMEZ" },
  { countryId: 8, name: "Julio Enciso", role: 2 as const, position: "MF", symbol: "ENCISO" },
  { countryId: 9, name: "Jude Bellingham", role: 1 as const, position: "MF", symbol: "BELLINGHAM" },
  { countryId: 9, name: "Harry Kane", role: 0 as const, position: "FW", symbol: "KANE" },
  { countryId: 9, name: "Ethan Nwaneri", role: 2 as const, position: "MF", symbol: "NWANERI" },
  { countryId: 10, name: "Kylian Mbappé", role: 1 as const, position: "FW", symbol: "MBAPPE" },
  { countryId: 10, name: "Aurélien Tchouaméni", role: 0 as const, position: "MF", symbol: "TCHOUAMENI" },
  { countryId: 10, name: "Warren Zaïre-Emery", role: 2 as const, position: "MF", symbol: "ZAIREEMERY" },
  { countryId: 11, name: "Joško Gvardiol", role: 1 as const, position: "MF", symbol: "GVARDIOL" },
  { countryId: 11, name: "Luka Modrić", role: 0 as const, position: "MF", symbol: "MODRIC" },
  { countryId: 11, name: "Luka Vušković", role: 2 as const, position: "MF", symbol: "VUSKOVIC" },
  { countryId: 12, name: "Erling Haaland", role: 1 as const, position: "FW", symbol: "HAALAND" },
  { countryId: 12, name: "Martin Ødegaard", role: 0 as const, position: "MF", symbol: "ODEGAARD" },
  { countryId: 12, name: "Sindre Walle Egeli", role: 2 as const, position: "FW", symbol: "EGELI" },
  { countryId: 13, name: "Bruno Fernandes", role: 1 as const, position: "MF", symbol: "FERNANDES" },
  { countryId: 13, name: "Rúben Dias", role: 0 as const, position: "MF", symbol: "DIAS" },
  { countryId: 13, name: "Rodrigo Mora", role: 2 as const, position: "FW", symbol: "RMORA" },
  { countryId: 14, name: "Florian Wirtz", role: 1 as const, position: "MF", symbol: "WIRTZ" },
  { countryId: 14, name: "Joshua Kimmich", role: 0 as const, position: "MF", symbol: "KIMMICH" },
  { countryId: 14, name: "Brajan Gruda", role: 2 as const, position: "FW", symbol: "GRUDA" },
  { countryId: 15, name: "Virgil van Dijk", role: 1 as const, position: "DF", symbol: "VANDIJK" },
  { countryId: 15, name: "Frenkie de Jong", role: 0 as const, position: "MF", symbol: "DEJONG" },
  { countryId: 15, name: "Jorrel Hato", role: 2 as const, position: "DF", symbol: "HATO" },
  { countryId: 16, name: "Granit Xhaka", role: 1 as const, position: "MF", symbol: "XHAKA" },
  { countryId: 16, name: "Manuel Akanji", role: 0 as const, position: "MF", symbol: "AKANJI" },
  { countryId: 16, name: "Ardon Jashari", role: 2 as const, position: "MF", symbol: "JASHARI" },
  { countryId: 17, name: "Andrew Robertson", role: 1 as const, position: "DF", symbol: "ROBERTSON" },
  { countryId: 17, name: "John McGinn", role: 0 as const, position: "MF", symbol: "MCGINN" },
  { countryId: 17, name: "Ben Doak", role: 2 as const, position: "FW", symbol: "DOAK" },
  { countryId: 18, name: "Lamine Yamal", role: 1 as const, position: "FW", symbol: "YAMAL" },
  { countryId: 18, name: "Rodri", role: 0 as const, position: "MF", symbol: "RODRI" },
  { countryId: 18, name: "Pau Cubarsí", role: 2 as const, position: "DF", symbol: "CUBARSI" },
  { countryId: 19, name: "David Alaba", role: 1 as const, position: "DF", symbol: "ALABA" },
  { countryId: 19, name: "Marcel Sabitzer", role: 0 as const, position: "MF", symbol: "SABITZER" },
  { countryId: 19, name: "Oghenetejiri Adejenughure", role: 2 as const, position: "MF", symbol: "ADEJENUGHURE" },
  { countryId: 20, name: "Kevin De Bruyne", role: 1 as const, position: "MF", symbol: "DEBRUYNE" },
  { countryId: 20, name: "Romelu Lukaku", role: 0 as const, position: "MF", symbol: "LUKAKU" },
  { countryId: 20, name: "Mika Godts", role: 2 as const, position: "FW", symbol: "GODTS" },
  { countryId: 21, name: "Edin Džeko", role: 1 as const, position: "MF", symbol: "DZEKO" },
  { countryId: 21, name: "Sead Kolašinac", role: 0 as const, position: "MF", symbol: "KOLASINAC" },
  { countryId: 21, name: "Kerim Alajbegović", role: 2 as const, position: "MF", symbol: "ALAJBEGOVIC" },
  { countryId: 22, name: "Alexander Isak", role: 1 as const, position: "MF", symbol: "ISAK" },
  { countryId: 22, name: "Victor Lindelöf", role: 0 as const, position: "MF", symbol: "LINDELOF" },
  { countryId: 22, name: "Roony Bardghji", role: 2 as const, position: "MF", symbol: "BARDGHJI" },
  { countryId: 23, name: "Hakan Çalhanoğlu", role: 1 as const, position: "MF", symbol: "CALHANOGLU" },
  { countryId: 23, name: "Çağlar Söyüncü", role: 0 as const, position: "MF", symbol: "SOYUNCU" },
  { countryId: 23, name: "Arda Güler", role: 2 as const, position: "FW", symbol: "GULER" },
  { countryId: 24, name: "Tomáš Souček", role: 1 as const, position: "MF", symbol: "SOUCEK" },
  { countryId: 24, name: "Vladimír Coufal", role: 0 as const, position: "MF", symbol: "COUFAL" },
  { countryId: 24, name: "Adam Karabec", role: 2 as const, position: "MF", symbol: "KARABEC" },
  { countryId: 25, name: "Achraf Hakimi", role: 1 as const, position: "DF", symbol: "HAKIMI" },
  { countryId: 25, name: "Hakim Ziyech", role: 0 as const, position: "FW", symbol: "ZIYECH" },
  { countryId: 25, name: "Eliesse Ben Seghir", role: 2 as const, position: "FW", symbol: "BENSEGHIR" },
  { countryId: 26, name: "Youssef Msakni", role: 1 as const, position: "FW", symbol: "MSAKNI" },
  { countryId: 26, name: "Montassar Talbi", role: 0 as const, position: "MF", symbol: "TALBI" },
  { countryId: 26, name: "Mohamed Ali Ben Romdhane", role: 2 as const, position: "MF", symbol: "BENROMDHANE" },
  { countryId: 27, name: "Mohamed Salah", role: 1 as const, position: "FW", symbol: "SALAH" },
  { countryId: 27, name: "Ahmed Hegazi", role: 0 as const, position: "MF", symbol: "HEGAZI" },
  { countryId: 27, name: "Omar Faied", role: 2 as const, position: "MF", symbol: "FAIED" },
  { countryId: 28, name: "Riyad Mahrez", role: 1 as const, position: "FW", symbol: "MAHREZ" },
  { countryId: 28, name: "Ismaël Bennacer", role: 0 as const, position: "MF", symbol: "BENNACER" },
  { countryId: 28, name: "Ibrahim Maza", role: 2 as const, position: "MF", symbol: "MAZA" },
  { countryId: 29, name: "Mohammed Kudus", role: 1 as const, position: "MF", symbol: "KUDUS" },
  { countryId: 29, name: "Thomas Partey", role: 0 as const, position: "MF", symbol: "PARTEY" },
  { countryId: 29, name: "Ernest Nuamah", role: 2 as const, position: "FW", symbol: "NUAMAH" },
  { countryId: 30, name: "Ryan Mendes", role: 1 as const, position: "MF", symbol: "MENDES" },
  { countryId: 30, name: "Vozinha", role: 0 as const, position: "MF", symbol: "VOZINHA" },
  { countryId: 30, name: "Deroy Duarte", role: 2 as const, position: "MF", symbol: "DUARTE" },
  { countryId: 31, name: "Percy Tau", role: 1 as const, position: "MF", symbol: "TAU" },
  { countryId: 31, name: "Ronwen Williams", role: 0 as const, position: "MF", symbol: "WILLIAMS" },
  { countryId: 31, name: "Shandre Campbell", role: 2 as const, position: "FW", symbol: "CAMPBELL" },
  { countryId: 32, name: "Franck Kessié", role: 1 as const, position: "MF", symbol: "KESSIE" },
  { countryId: 32, name: "Sébastien Haller", role: 0 as const, position: "MF", symbol: "HALLER" },
  { countryId: 32, name: "Yan Diomande", role: 2 as const, position: "MF", symbol: "DIOMANDE" },
  { countryId: 33, name: "Sadio Mané", role: 1 as const, position: "FW", symbol: "MANE" },
  { countryId: 33, name: "Kalidou Koulibaly", role: 0 as const, position: "DF", symbol: "KOULIBALY" },
  { countryId: 33, name: "Amara Diouf", role: 2 as const, position: "MF", symbol: "DIOUF" },
  { countryId: 34, name: "Takefusa Kubo", role: 1 as const, position: "FW", symbol: "KUBO" },
  { countryId: 34, name: "Wataru Endō", role: 0 as const, position: "MF", symbol: "ENDO" },
  { countryId: 34, name: "Kota Takai", role: 2 as const, position: "DF", symbol: "TAKAI" },
  { countryId: 35, name: "Mehdi Taremi", role: 1 as const, position: "FW", symbol: "TAREMI" },
  { countryId: 35, name: "Alireza Jahanbakhsh", role: 0 as const, position: "MF", symbol: "JAHANBAKHSH" },
  { countryId: 35, name: "Mohammad Ghorbani", role: 2 as const, position: "MF", symbol: "GHORBANI" },
  { countryId: 36, name: "Abbosbek Fayzullaev", role: 1 as const, position: "MF", symbol: "FAYZULLAEV" },
  { countryId: 36, name: "Eldor Shomurodov", role: 0 as const, position: "MF", symbol: "SHOMURODOV" },
  { countryId: 36, name: "Abdukodir Khusanov", role: 2 as const, position: "MF", symbol: "KHUSANOV" },
  { countryId: 37, name: "Son Heung-min", role: 1 as const, position: "FW", symbol: "SON" },
  { countryId: 37, name: "Kim Min-jae", role: 0 as const, position: "DF", symbol: "KIM" },
  { countryId: 37, name: "Yang Min-hyeok", role: 2 as const, position: "MF", symbol: "YANG" },
  { countryId: 38, name: "Mousa Al-Tamari", role: 1 as const, position: "MF", symbol: "ALTAMARI" },
  { countryId: 38, name: "Ehsan Haddad", role: 0 as const, position: "MF", symbol: "HADDAD" },
  { countryId: 38, name: "Mahmoud Al-Mardi", role: 2 as const, position: "MF", symbol: "ALMARDI" },
  { countryId: 39, name: "Harry Souttar", role: 1 as const, position: "MF", symbol: "SOUTTAR" },
  { countryId: 39, name: "Mat Ryan", role: 0 as const, position: "MF", symbol: "RYAN" },
  { countryId: 39, name: "Nestory Irankunda", role: 2 as const, position: "FW", symbol: "IRANKUNDA" },
  { countryId: 40, name: "Akram Afif", role: 1 as const, position: "FW", symbol: "AFIF" },
  { countryId: 40, name: "Hassan Al-Haydos", role: 0 as const, position: "MF", symbol: "ALHAYDOS" },
  { countryId: 40, name: "Ahmed Al-Rawi", role: 2 as const, position: "MF", symbol: "ALRAWI" },
  { countryId: 41, name: "Salem Al-Dawsari", role: 1 as const, position: "FW", symbol: "ALDAWSARI" },
  { countryId: 41, name: "Ali Al-Bulaihi", role: 0 as const, position: "MF", symbol: "ALBULAIHI" },
  { countryId: 41, name: "Talal Haji", role: 2 as const, position: "MF", symbol: "HAJI" },
  { countryId: 42, name: "Adalberto Carrasquilla", role: 1 as const, position: "MF", symbol: "CARRASQUILLA" },
  { countryId: 42, name: "Aníbal Godoy", role: 0 as const, position: "MF", symbol: "GODOY" },
  { countryId: 42, name: "Kahiser Lenis", role: 2 as const, position: "MF", symbol: "LENIS" },
  { countryId: 43, name: "Leandro Bacuna", role: 1 as const, position: "MF", symbol: "BACUNA" },
  { countryId: 43, name: "Cuco Martina", role: 0 as const, position: "MF", symbol: "MARTINA" },
  { countryId: 43, name: "Jearl Margaritha", role: 2 as const, position: "MF", symbol: "MARGARITHA" },
  { countryId: 44, name: "Duckens Nazon", role: 1 as const, position: "MF", symbol: "NAZON" },
  { countryId: 44, name: "Johnny Placide", role: 0 as const, position: "MF", symbol: "PLACIDE" },
  { countryId: 44, name: "Louicius Don Deedson", role: 2 as const, position: "MF", symbol: "DEEDSON" },
  { countryId: 45, name: "Chris Wood", role: 1 as const, position: "MF", symbol: "WOOD" },
  { countryId: 45, name: "Liberato Cacace", role: 0 as const, position: "MF", symbol: "CACACE" },
  { countryId: 45, name: "Tyler Bindon", role: 2 as const, position: "MF", symbol: "BINDON" },
  { countryId: 46, name: "Chancel Mbemba", role: 1 as const, position: "MF", symbol: "MBEMBA" },
  { countryId: 46, name: "Cédric Bakambu", role: 0 as const, position: "MF", symbol: "BAKAMBU" },
  { countryId: 46, name: "Noah Sadiki", role: 2 as const, position: "MF", symbol: "SADIKI" },
  { countryId: 47, name: "Aymen Hussein", role: 1 as const, position: "MF", symbol: "HUSSEIN" },
  { countryId: 47, name: "Jalal Hassan", role: 0 as const, position: "MF", symbol: "HASSAN" },
  { countryId: 47, name: "Ali Jasim", role: 2 as const, position: "MF", symbol: "JASIM" },
] as const;

// Countries data (matching on-chain deploy order — PITCH canonical order)
export const COUNTRIES = [
  { id: 0, name: "United States", symbol: "USA", flag: "🇺🇸", group: "A" },
  { id: 1, name: "Mexico", symbol: "MEX", flag: "🇲🇽", group: "A" },
  { id: 2, name: "Canada", symbol: "CAN", flag: "🇨🇦", group: "A" },
  { id: 3, name: "England", symbol: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "B" },
  { id: 4, name: "France", symbol: "FRA", flag: "🇫🇷", group: "B" },
  { id: 5, name: "Croatia", symbol: "CRO", flag: "🇭🇷", group: "B" },
  { id: 6, name: "Norway", symbol: "NOR", flag: "🇳🇴", group: "B" },
  { id: 7, name: "Portugal", symbol: "POR", flag: "🇵🇹", group: "C" },
  { id: 8, name: "Germany", symbol: "GER", flag: "🇩🇪", group: "C" },
  { id: 9, name: "Netherlands", symbol: "NED", flag: "🇳🇱", group: "C" },
  { id: 10, name: "Switzerland", symbol: "SUI", flag: "🇨🇭", group: "C" },
  { id: 11, name: "Scotland", symbol: "SCO", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", group: "D" },
  { id: 12, name: "Spain", symbol: "ESP", flag: "🇪🇸", group: "D" },
  { id: 13, name: "Austria", symbol: "AUT", flag: "🇦🇹", group: "D" },
  { id: 14, name: "Belgium", symbol: "BEL", flag: "🇧🇪", group: "D" },
  { id: 15, name: "Bosnia & Herzegovina", symbol: "BIH", flag: "🇧🇦", group: "E" },
  { id: 16, name: "Sweden", symbol: "SWE", flag: "🇸🇪", group: "E" },
  { id: 17, name: "Türkiye", symbol: "TUR", flag: "🇹🇷", group: "E" },
  { id: 18, name: "Czechia", symbol: "CZE", flag: "🇨🇿", group: "E" },
  { id: 19, name: "Argentina", symbol: "ARG", flag: "🇦🇷", group: "F" },
  { id: 20, name: "Brazil", symbol: "BRA", flag: "🇧🇷", group: "F" },
  { id: 21, name: "Ecuador", symbol: "ECU", flag: "🇪🇨", group: "F" },
  { id: 22, name: "Uruguay", symbol: "URU", flag: "🇺🇾", group: "F" },
  { id: 23, name: "Colombia", symbol: "COL", flag: "🇨🇴", group: "G" },
  { id: 24, name: "Paraguay", symbol: "PAR", flag: "🇵🇾", group: "G" },
  { id: 25, name: "Morocco", symbol: "MAR", flag: "🇲🇦", group: "G" },
  { id: 26, name: "Tunisia", symbol: "TUN", flag: "🇹🇳", group: "G" },
  { id: 27, name: "Egypt", symbol: "EGY", flag: "🇪🇬", group: "H" },
  { id: 28, name: "Algeria", symbol: "ALG", flag: "🇩🇿", group: "H" },
  { id: 29, name: "Ghana", symbol: "GHA", flag: "🇬🇭", group: "H" },
  { id: 30, name: "Cape Verde", symbol: "CPV", flag: "🇨🇻", group: "H" },
  { id: 31, name: "South Africa", symbol: "RSA", flag: "🇿🇦", group: "I" },
  { id: 32, name: "Côte d'Ivoire", symbol: "CIV", flag: "🇨🇮", group: "I" },
  { id: 33, name: "Senegal", symbol: "SEN", flag: "🇸🇳", group: "I" },
  { id: 34, name: "Japan", symbol: "JPN", flag: "🇯🇵", group: "I" },
  { id: 35, name: "Iran", symbol: "IRN", flag: "🇮🇷", group: "J" },
  { id: 36, name: "Uzbekistan", symbol: "UZB", flag: "🇺🇿", group: "J" },
  { id: 37, name: "South Korea", symbol: "KOR", flag: "🇰🇷", group: "J" },
  { id: 38, name: "Jordan", symbol: "JOR", flag: "🇯🇴", group: "J" },
  { id: 39, name: "Australia", symbol: "AUS", flag: "🇦🇺", group: "K" },
  { id: 40, name: "Qatar", symbol: "QAT", flag: "🇶🇦", group: "K" },
  { id: 41, name: "Saudi Arabia", symbol: "SAU", flag: "🇸🇦", group: "K" },
  { id: 42, name: "Panama", symbol: "PAN", flag: "🇵🇦", group: "K" },
  { id: 43, name: "Curaçao", symbol: "CUW", flag: "🇨🇼", group: "L" },
  { id: 44, name: "Haiti", symbol: "HAI", flag: "🇭🇹", group: "L" },
  { id: 45, name: "New Zealand", symbol: "NZL", flag: "🇳🇿", group: "L" },
  { id: 46, name: "DR Congo", symbol: "COD", flag: "🇨🇩", group: "L" },
  { id: 47, name: "Iraq", symbol: "IRQ", flag: "🇮🇶", group: "L" },
] as const;

// Shared flag URL mapper (flagcdn.com) — single source of truth
export function getFlagUrl(symbol: string, size: "w40" | "w80" = "w40"): string {
  const map: Record<string, string> = {
    ALG: "dz", ARG: "ar", AUS: "au", AUT: "at",
    BEL: "be", BIH: "ba", BRA: "br", CAN: "ca",
    CIV: "ci", COD: "cd", COL: "co", CPV: "cv",
    CRO: "hr", CUW: "cw", CZE: "cz", ECU: "ec",
    EGY: "eg", ENG: "gb-eng", ESP: "es", FRA: "fr",
    GER: "de", GHA: "gh", HAI: "ht", IRN: "ir",
    IRQ: "iq", JOR: "jo", JPN: "jp", KOR: "kr",
    MAR: "ma", MEX: "mx", NED: "nl", NOR: "no",
    NZL: "nz", PAN: "pa", PAR: "py", POR: "pt",
    QAT: "qa", RSA: "za", SAU: "sa", SCO: "gb-sct",
    SEN: "sn", SUI: "ch", SWE: "se", TUN: "tn",
    TUR: "tr", URU: "uy", USA: "us", UZB: "uz",
  };
  const code = map[symbol] || "un";
  return `https://flagcdn.com/${size}/${code}.png`;
}
